# Generated by Django 3.2.3 on 2024-06-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_movielist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('romance', 'Romance'), ('scifi', 'Scifi'), ('fantasy', 'Fantasy')], max_length=100),
        ),
    ]
