# Generated by Django 3.2.3 on 2024-06-25 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_movie_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='image_card',
            new_name='image_banner',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='image_cover',
            new_name='image_poster',
        ),
    ]
